name: dev
variables:
  - name: accessToken
    value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI0NiIsImVtYWlsIjoiaGFya2FpLnRhbWFzQGlubm9zbWFydGtmdC5odSIsInVuaXF1ZV9uYW1lIjoiVGFtYXMiLCJuYW1laWQiOiJoYXJrYWkudGFtYXNAaW5ub3NtYXJ0a2Z0Lmh1IiwibmJmIjoxNzg2Nzk1Mzg3LCJleHAiOjE3ODY3OTU5ODcsImlhdCI6MTc4Njc5NTM4NywiaXNzIjoiSW5ub3NtYXJ0IEtmdC4iLCJhdWQiOiJJbm5vQ2hhdFVzZXJzIn0.EKcbkmGciwpI9hhhGVzObA5baN-f-8FXVgHamwaA9bQ
  - name: url
    value: http://172.22.4.22:8082
  - name: email
    value: harkai.tamas@innosmartkft.hu
  - name: passwordHash
    value: 3c9909afec25354d551dae21590bb26e38d53f2173b8d3dc3eee4c047e7ab1c1eb8b85103e3be7ba613b31bb5c9c36214dc9f14a42fd7a2fdb84856bca5c44c2
  - name: sessionId
    value: b6f737e9-9f67-4731-ae49-71cd7ed032ed
